services:
  - type: web
    name: pms-backend
    env: docker
    region: oregon
    plan: starter

    docker:
      dockerfile: Dockerfile

    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.ldxukptpjddrtzcvvcpm.supabase.co:5432/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"

    port: 8080

    buildCommand: mvn clean package -DskipTests

    healthCheckPath: /actuator/health
